# Generated by Django 2.0 on 2018-08-10 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=80)),
                ('business_email', models.EmailField(max_length=254)),
                ('business_website', models.CharField(max_length=80)),
                ('business_phone', models.CharField(max_length=80)),
            ],
        ),
    ]
